### ISSUE TITLE
Add bus arrival/departure times to School Modify Form, automatically update route bus stop times

### ISSUE THREAD

**Issue by kyratichan** [jqyang42/ht_buses#217]
School modify: Administrators will be able to modify school records. Changes to a school’s bus arrival/departure times should automatically update associated route bus stop pickup/dropoff times, as they are derived values.

**Comment by kyratichan** [comment]
Status Update: Arrival/Departure Time columns have been added to the table.

**Comment by kyratichan** [comment]
@jqyang42 school modify not saving updated bus arrival / departure times in PUT request

**Comment by jqyang42** [comment]
@eve658 update school/details get api to use xx:xx format
