### ISSUE TITLE
Remap data on frontend for tables

### ISSUE THREAD

**Issue by kyratichan** [jqyang42/ht_buses#243]
- For all Students table views that show a Route column: either this value would be Unassigned, Out of Range (if student is assigned to a route, but is not within range of any bus stops), or the actual route name (if student is within range of 1+ bus stops on that route)
- To calculate if a Student is Out of Range of all bus stops, double check with Thomas on how he is implementing the distance calculations
- For all Routes table views, Kyra has added a new Status column: either this value would be Incomplete or Complete (not sure what backend sends, but this should probably be a boolean and you just need to convert it to Incomplete or Complete, double check what backend returns with Evelyn actually)

**Comment by jqyang42** [comment]
might need to include some of this in api calls - unassigned and stuff used in other fields (eg student details)
