### ISSUE TITLE
Parent contact info (name, email, home address, phone number) not displayed in student detail

### ISSUE THREAD

**Issue by ThomasQuesadilla** [jqyang42/ht_buses#418]
Parent contact info (name, email, home address, phone number) should be displayed in student detail. Assigning evelyn incase api needs to change.

**Comment by eve658** [comment]
![image](https://user-images.githubusercontent.com/57291458/159148413-471fd8ba-a74e-4121-a503-7c796137bfcf.png)

**Comment by eve658** [comment]
![image](https://user-images.githubusercontent.com/57291458/159148576-7b17c1cc-2474-45c5-8586-4ac4ba26f05d.png)
