### ISSUE TITLE
Create Transit Log View UI

### ISSUE THREAD

**Issue by kyratichan** [jqyang42/ht_buses#498]
It should be possible for administrators, drivers, and appropriate school
staff to view a history of bus runs as inferred by start/stop events. This tabular view
should show driver, bus number, school, route, direction (to or from school), start
date/time, and duration (or “ongoing” for runs still in transit). School staff should
only see records relating to schools they manage. Drivers, schools, and routes should
link to their respective detail views (reqs 3.3, 2.3, 4.3). The view should be sortable by
all fields and filterable by bus number, driver, school, and route.

**Comment by jqyang42** [comment]
on branch `transit-ui`

**Comment by eve658** [comment]
api url: `blah-blah/api/logs?page=&order_by=&sort_by=&q=`

JSON example: 

```
"logs": [
        {
            "id": 1,
            "route_name": "Log Testing",
            "school_name": "Duke University",
            "bus_number": 1,
            "user": {
                "id": 2,
                "first_name": "Admin",
                "last_name": "Example"
            },
            "date": "2022-03-29",
            "start_time": "02:08:",
            "duration": "00:00",
            "pickup": false
        }
```

**Comment by eve658** [comment]
Create a Log:
api url: `blah-blah/api/logs/create`

JSON example:
```

{
    "log": {
        "bus_number": 1,
        "user_id": 1,
        "route_id": 1,
        "pickup": false
    }
}
```

**Comment by eve658** [comment]
Update a Log:
api url: `blah-blah/api/logs/update?id=1`

The id is the id of the log.

**Comment by eve658** [comment]
The Detail Logs:

Driver (id parameter is for user id):
api url: `http://localhost:8000/api/logs/driver?id=2&page=1&sort_by&order_by&q=`

Route (id parameter is route id):
api url: `http://localhost:8000/api/logs/route?id=2&page=1&sort_by&order_by&q=`

School (id parameter is school id):
api url: `http://localhost:8000/api/logs/school?id=2&page=1&sort_by&order_by&q=`
