### ISSUE TITLE
Update Database Models

### ISSUE THREAD

**Issue by eve658** [jqyang42/ht_buses#500]
Update Database Models
- Remove is_parent parameter
- Add new role of Student, where role = 5 is student role

**Comment by kyratichan** [comment]
For the transit status table: frontend tables have the following fields
- Route: route.color_id, route.id, and route.name
- Bus #: bus_number
- Driver: driver

**Comment by kyratichan** [comment]
For the transit log table: frontend tables have the following fields
- Driver: driver
- Bus #: bus_number
- School: school_name
- Route: route.color_id, route.id, and route.name
- Direction: pickup (boolean for direction, true if pickup, false if dropoff)
- Start Time: start_time
- Duration: duration
