### ISSUE TITLE
enforce 1 active run at a time per route, with 1 bus and 1 driver

### ISSUE THREAD

**Issue by jqyang42** [jqyang42/ht_buses#533]
on the log/create api, backend will check if it violates the rule. if so, backend will flag an error, and frontend will display a banner

**Comment by jqyang42** [comment]
alternatively:
we can disable the start button if theres already a run happening
in that case i'd just call some api you have that tells me if a run already exists for that route or user 
i think bus number would still need to be checked in the log/create api

**Comment by kyratichan** [comment]
i believe this is already done but testing needs to be done to validate this bc there may be bugs

**Comment by kyratichan** [comment]
so actually it seems like we cannot do the start/stop button switch bc fern said u can start a new run it just automatically stops the previous run. so i believe fern made a separate ticket for this but ill keep this open just in case.
