### ISSUE TITLE
BUGS: Add Student on General User Detail

### ISSUE THREAD

**Issue by kyratichan** [jqyang42/ht_buses#577]
- Email does not show up in Students table until refresh
- Clicking on Add Student a second time deletes the student email field all of a sudden

**Comment by kyratichan** [comment]
@ferncorona i think you should look into adding the student email and phone fields with the refs that you have on all the other fields since i think that might be the problem??? honestly dont know why the fields completely disappear from the form though

**Comment by kyratichan** [comment]
** this may be an issue with threading instead actually **

**Comment by jqyang42** [comment]
threading count has been reduced, and i dont think i can reproduce it?

**Comment by kyratichan** [comment]
update: solved
