### ISSUE TITLE
Routes view does not show buses in transit 

### ISSUE THREAD

**Issue by ferncorona** [jqyang42/ht_buses#601]
<img width="1180" alt="Screen Shot 2022-04-11 at 1 50 50 AM" src="https://user-images.githubusercontent.com/67384518/162673053-ca96a08f-d3f9-4ecf-9d38-d1617ddae8e6.png">
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/67384518/162673122-71ae1bad-f9d0-4548-90ba-f9ce16d8d4a5.png">

**Comment by eve658** [comment]
Is it supposed to show in routes view or route detail? I think we have it on route detail?

**Comment by jqyang42** [comment]
![image](https://user-images.githubusercontent.com/48226853/162791463-bbe98a08-1147-4b48-95d9-1384a1f97454.png)
yes i think we need it.

if the routes api returns it, kyra and i can display it
