### ISSUE TITLE
routes big table/view api needs more data: bus_number, in_transit, driver

### ISSUE THREAD

**Issue by jqyang42** [jqyang42/ht_buses#606]
![image](https://user-images.githubusercontent.com/48226853/162806805-8bb4029a-153a-4f9b-b3bb-b7f4ee5babaa.png)

**Comment by jqyang42** [comment]
use `routes-view-fix` branch

**Comment by eve658** [comment]
![image](https://user-images.githubusercontent.com/57291458/162826741-77d82baa-a2de-45ee-8c7e-310612ddc5c5.png)
